test_crit (__main__.TestCharacter) ... ERROR
test_init (__main__.TestCharacter) ... ERROR
test_name (__main__.TestCharacter) ... ok
test_weapon (__main__.TestCharacter) ... ERROR
test_init (__main__.TestWeapon) ... ERROR
test_name (__main__.TestWeapon) ... ERROR
test_unarmed (__main__.TestWeapon) ... ERROR

======================================================================
ERROR: test_crit (__main__.TestCharacter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\patte\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 1337, in patched
    return func(*newargs, **newkeywargs)
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\test_exercice.py", line 76, in test_crit
    dmg, crit = self.foo.compute_damage(self.bar)
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\game.py", line 60, in compute_damage
    if attacker.weapon == None:
AttributeError: 'Character' object has no attribute 'weapon'

======================================================================
ERROR: test_init (__main__.TestCharacter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\test_exercice.py", line 65, in test_init
    self.assertEqual(self.foo.weapon.name, "Unarmed")
AttributeError: 'Character' object has no attribute 'weapon'

======================================================================
ERROR: test_weapon (__main__.TestCharacter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\test_exercice.py", line 56, in test_weapon
    self.assertEqual(self.bar.weapon.name, "Unarmed")
AttributeError: 'NoneType' object has no attribute 'name'

======================================================================
ERROR: test_init (__main__.TestWeapon)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\test_exercice.py", line 19, in setUp
    self.w4 = Weapon.make_unarmed()
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\game.py", line 31, in make_unarmed
    return Weapon("Unarmed", UNARMED_POWER)
NameError: name 'UNARMED_POWER' is not defined

======================================================================
ERROR: test_name (__main__.TestWeapon)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\test_exercice.py", line 19, in setUp
    self.w4 = Weapon.make_unarmed()
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\game.py", line 31, in make_unarmed
    return Weapon("Unarmed", UNARMED_POWER)
NameError: name 'UNARMED_POWER' is not defined

======================================================================
ERROR: test_unarmed (__main__.TestWeapon)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\test_exercice.py", line 19, in setUp
    self.w4 = Weapon.make_unarmed()
  File "c:\Users\patte\OneDrive\Documents\Polytechnique\Intro à la programmation\Exercices\c03-ch11-1-exercices-JerPatterson\game.py", line 31, in make_unarmed
    return Weapon("Unarmed", UNARMED_POWER)
NameError: name 'UNARMED_POWER' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (errors=6)
